version: '3'

services:
  llm-sandbox:
    image: msrajawat298/llm-environment
    restart: always
    ports:
      - "8080:8501"
    volumes:
      - .:/app
    command: /bin/sh -c "streamlit run /app/main.py && tail -f /dev/null"
